config/routes.rb
Rails.application.routes.draw do

  scope '/:locale', locale: /#{I18n.available_locales.join('|')}/ do
    root to: 'application#home'
  end

  get 'getstarted/thankyou'

  get 'getstarted/starter' => redirect("https://starterplan.carrd.co/") # Recopie ca pour les deux autres plans
  get 'getstarted/basic_confirm', to: 'getstarted#basic_confirm'

  get 'getstarted/standard'=> redirect("https://standardplan.carrd.co/")
  get 'getstarted/intermediate_confirm', to: 'getstarted#intermediate_confirm'

  get 'getstarted/plus'=> redirect("https://plusplan.carrd.co/")
  get 'getstarted/pro_confirm', to: 'getstarted#pro_confirm'

  get '/faq', to: 'pages#faq'
  get '/blog', to: 'pages#blog'
  get '/jobs', to: 'pages#jobs'
  get '/terms', to: 'pages#terms'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'
end

app/models/concerns/stripe_tool.rb
  def self.create_membership(email: email, stripe_token: stripe_token, plan: plan)
    Stripe::Customer.create(
      email: email,
      source: stripe_token,
      plan: plan
    )
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_locale

  def home
  end

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/getstarted_controller.rb
class GetstartedController < ApplicationController
  def basic
  end

  def basic_confirm
  end

  def intermediate
  end

  def intermediate_confirm
  end

  def pro
  end

  def pro_confirm
  end

  def thankyou
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def faq
  end

  def blog
  end

  def jobs
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/getstarted_helper.rb
module GetstartedHelper
end

app/views/application/_banner.html.erb
<div id="banner">
  <h1 class="banner-title">
    Votre <strong>fournisseur-partenaire</strong> en <br> <span class="insta-word"> matières premières alimentaires.</span>
  </h1> <!-- End .banner-title -->

  <p class="banner-desc">
    <span class="hidden-xs"> Depuis 1946, la Maison Majean assure un service de livraison professionnel
    <br>
    et fournit des produits de qualité aux boulangers-patissiers traditionnels de nos régions.
    <br>
    Un suivi sur mesure, dans le respect des traditions et toujours au service du savoir-faire de nos clients.
    <br>

    </span>
    La sélection et livraison dans vos ateliers des meilleurs produits de matières premières alimentaire en boulangerie-patiserie, c'est <span class="super-social-word">notre métier.</span>
    </p>

  <button class="primary-button">
    <a href="#why"><%= t('landing.buttons.primary_button') %></a>
  </button>
</div>

app/views/application/_contact.html.erb
<div id="contact">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="contact-us">
          Architects, Architecture Firms, Product Designers &#038; more
          <br><br>
          <div class="we-can-help">We can help you...</div>
        </div>
      </div>
    </div>
  </div>
  <%= image_tag("iphone-mockup-final.png", class: "iphone-mock-up hidden-xs") %>
</div>

app/views/application/_how.html.erb
<div id="how">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2 class="section-title">How it works?</h2>
      </div>
    </div>

    <div class="row feature">
      <!-- Illustration mobile & desktop -->
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <%= image_tag("illu-test.png", class: "feature-illu") %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="feature-content">
          <div class="feature-content-vert">
            <h3 class="feature-title">Develop an Instagram Strategy</h3>
            <div class="features-desc"> Through an online form, our team will get a better understanding of how your business works: where your target audience is located, what they are interested in, and which other accounts they follow.</div>
          </div>
        </div>
      </div>
    </div><!-- End .row .feature -->

    <div class="row feature">
      <!-- Illustration mobile -->
      <div class="hidden-sm hidden-md hidden-lg">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <%= image_tag("illu-test.png", class: "feature-illu") %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="feature-content">
          <div class="feature-content-vert">
            <h3 class="feature-title">Configuration of Your Campaign</h3>
            <div class="features-desc">Next we will configure the chosen targeting strategy into our software. Your account will then start interacting automatically with your target audience. These interactions are most often a combination of liking pictures and following users within a specific market.</div>
          </div>
        </div>
      </div>
      <!-- Illustration desktop -->
      <div class="hidden-xs">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <%= image_tag("illu-test.png", class: "feature-illu") %>
        </div>
      </div>
    </div><!-- End .row .feature -->

    <div class="row feature">
      <!-- Illustration mobile & desktop -->
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <%= image_tag("illu-test.png", class: "feature-illu") %>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="feature-content">
          <div class="feature-content-vert">
            <h3 class="feature-title">Increased Brand Awareness</h3>
            <div class="features-desc">As soon as the first interactions are initiated, results are visible instantly. Your Instagram profile will grow faster by receiving more likes, comments and followers. There will be a growing stream of traffic to your website as more users discover your profile.</div>
          </div>
        </div>
      </div>
    </div><!-- End .row .feature -->

    <div class="row feature">
      <!-- Illustration mobile -->
      <div class="hidden-sm hidden-md hidden-lg">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <%= image_tag("illu-test.png", class: "feature-illu") %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="feature-content">
          <div class="feature-content-vert">
            <h3 class="feature-title">Increased Sales Conversions</h3>
            <div class="features-desc">Once your campaign launches, the amplification machine starts. Targeted followers are leads to your business. Leads can be turn into loyal customers.</div>
          </div>
        </div>
      </div>
      <!-- Illustration desktop -->
      <div class="hidden-xs">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
          <%= image_tag("illu-test.png", class: "feature-illu") %>
        </div>
      </div>
    </div> <!-- End .row .feature -->
  </div>
</div>

app/views/application/_pricing.html.erb
<div id="pricing">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="card-pricing">
          <div class="card-pricing-content">
            <div class="amount-followers">
              <p><strong>700 - 1000</strong> <br> <span>targeted Followers per month</span></p>
            </div>
            <ul>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Follow / Unfollow</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Like</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Limited support</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Monthly report</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-unchecked"></i>
                <p>Comments</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-unchecked"></i>
                <p>Direct Messages</p>
              </li>
            </ul>
          </div>
          <div class="card-pricing-footer">
            <h3 class="pricing-title">STARTER</h3>
            <div class="price">$ 59</div>
            <button class="primary-button pricing-button">
              <%= link_to '3-day free trial', getstarted_starter_path %>
            </button>
          </div>
        </div>
        <div class="cup-coffee text-center">
          *or 1 cup of <%= image_tag("emoji-coffee.png", class: "emoji") %> a day
          <%= image_tag("emoji-smile.png", class: "emoji") %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="most-popular">Most popular</div>
        <div class="card-pricing">
          <div class="card-pricing-content">
            <ul>
              <li class="pricing-spec amount-followers">
                <p><strong>1000 - 1500</strong> <br> <span>targeted Followers per month</span></p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Follow / Unfollow</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Like</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Limited support</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Monthly report</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Comments</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-unchecked"></i>
                <p>Direct Messages</p>
              </li>
            </ul>
          </div>
          <div class="card-pricing-footer">
            <h3 class="pricing-title">STANDARD</h3>
            <div class="price">$ 89</div>
            <button class="primary-button pricing-button">
              <%= link_to '3-day free trial', getstarted_standard_path %>
            </button>
          </div>
        </div>
        <div class="cup-coffee text-center">
          *or 2 cup of <%= image_tag("emoji-coffee.png", class: "emoji") %> a day
          <%= image_tag("emoji-smile.png", class: "emoji") %>
        </div>
      </div>

      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
        <div class="card-pricing">
          <div class="card-pricing-content">
            <ul>
              <ul>
              <li class="pricing-spec amount-followers">
                <p><strong>+ 1500</strong> <br> <span>targeted Followers per month</span></p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Follow / Unfollow</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Like</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Unlimited support</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Monthly report</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Comments</p>
              </li>
              <li class="pricing-spec">
                <i class="fas fa-check-circle circle-checked"></i>
                <p>Direct Messages</p>
              </li>
            </ul>
            </ul>
          </div>
          <div class="card-pricing-footer">
            <h3 class="pricing-title">PLUS</h3>
            <div class="price">$ 159</div>
            <button class="primary-button pricing-button">
              <%= link_to '3-day free trial', getstarted_plus_path %>
            </button>
          </div>
        </div>
        <div class="cup-coffee text-center">
          *or 3 cup of <%= image_tag("emoji-coffee.png", class: "emoji") %> a day
          <%= image_tag("emoji-smile.png", class: "emoji") %>
        </div>
      </div>
    </div>
</div>

app/views/application/_why.html.erb
<div id="why">
  <div class="container text-center">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h2 class="section-title">Vima, un acteur local historique</h2>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div class="tututu text-center">
          <strong>VIMA</strong> est l'acronyme de Victor Majean, fondateur de VIMA S.A en 1985 et fils du créateur de l'affaire, Fernand Majean, en 1946. <br>
          Aujourd'hui encore, en 2018, la société reste familiale.
          <br><br>
          <br> En commençant historiquement avec la margarine alimentaire, notre gamme à destination des boulangers-patissiers s'est etoffée au fil des années pour couvrir aujourd'hui plus de 3000 références, en constante évolution et adaptation, mais toujours avec l'exigeance de la qualité.<br>
          On essaie
        </div>
      </div>

    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="card-type content-right">
          <%= image_tag("002-group.svg", class: "icon-card-type mlrauto-mobile") %>
          <h3>Architect</h3>
          <div class="card-type-desc">
            Are you an Instagram’s rising star or already an established
            <br>
            Architect? We will help you build an engaged online
            <br>
            community around your profile!
          </div>
          <ul>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Reach more followers in your niche
              <span class="left hidden-xs">•</span>
            </li>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Improve engagement on you content
              <span class="left hidden-xs">•</span>
            </li>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Get recognized in your industry
              <span class="left hidden-xs">•</span>
            </li>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Build a strong personal brand
              <span class="left hidden-xs">•</span>
            </li>
            <li>
              <span class="right hidden-sm hidden-md hidden-lg">•</span>
              Monetize your popularity
              <span class="left hidden-xs">•</span>
            </li>
          </ul>
          <button class="secondary-button"> <a href="#pricing">Get Started with <strong>Architect</strong></a></button>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="card-type content-left">
          <%= image_tag("001-employee.svg", class: "icon-card-type mlrauto-mobile") %>
          <h3>Architecture Firm</h3>
          <div class="card-type-desc">
            Is Instagram presence just a part of your Architecture business strategy?
            <br>
            We will help you reach your target audience and drive more sales to your business!
          </div>
          <ul >
            <li><span class="right">•</span>Grow your brand’s awareness</li>
            <li><span class="right">•</span>Drive more sales to your business</li>
            <li><span class="right">•</span>Connect with Top Architects from your industry</li>
            <li><span class="right">•</span>Improve customer engagement</li>
            <li><span class="right">•</span>Expand to new markets easily</li>
          </ul>
          <button class="secondary-button"> <a href="#pricing">Get Started with <strong>Architecture Firm</strong></a></button>
        </div>
      </div>
    </div>
  </div>
</div>

<hr>

app/views/application/home.html.erb
<!-- Navbar -->
<%= render 'shared/navbar' %>

<!-- Banner -->
<%= render "application/banner" %>

<!-- Why -->
<%= render "application/why" %>

<!-- How -->
<%= render "application/how" %>

<!-- Pricing -->
<%= render "application/pricing" %>

<!-- Contact -->
<%= render "application/contact" %>

<!-- Footer -->
<%= render 'shared/footer' %>

app/views/getstarted/basic.html.erb
<!-- Basic Form -->

<div class="text-center" id="banner">
  <div class="typeform-widget" data-url="https://brucewayne465.typeform.com/to/ctF3YE" data-transparency="100" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 500px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

  <button class="primary-button confirm-button">
    <%= link_to 'Confirm your plan', getstarted_basic_confirm_path %>
  </button>
</div>

app/views/getstarted/basic_confirm.html.erb
<button class="btn btn-primary btn-large" id="stripe-demo">Subscribe</button>

<script src="https://checkout.stripe.com/checkout.js"></script>
<script>
var handler = StripeCheckout.configure({
  key: "pk_test_1MCYLYHQDa4DwnBoKd5CqoaP",
  image: "https://stripe.com/img/documentation/checkout/marketplace.png",
  name: "Demo SaaS Site",
  description: "Pro Subscription ($29 per month)",
  panelLabel: "Subscribe",
  allowRememberMe: false
});

document.getElementById('stripe-demo').addEventListener('click', function(e) {
  handler.open();
  e.preventDefault();
});
</script>

app/views/getstarted/intermediate.html.erb
<!-- Intermediate Form -->

<div class="text-center" id="banner">
  <div class="typeform-widget" data-url="https://brucewayne465.typeform.com/to/m5FeUy" data-transparency="100" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 500px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

  <button class="primary-button confirm-button">
    <%= link_to 'Confirm your plan', getstarted_intermediate_confirm_path %>
  </button>
</div>

app/views/getstarted/intermediate_confirm.html.erb
intermediate_confirm.html.erb

app/views/getstarted/pro.html.erb
<!-- Pro Form -->

<div class="text-center" id="banner">
  <div class="typeform-widget" data-url="https://brucewayne465.typeform.com/to/basYMj" data-transparency="100" data-hide-headers=true data-hide-footer=true style="width: 100%; height: 500px;" > </div> <script> (function() { var qs,js,q,s,d=document, gi=d.getElementById, ce=d.createElement, gt=d.getElementsByTagName, id="typef_orm", b="https://embed.typeform.com/"; if(!gi.call(d,id)) { js=ce.call(d,"script"); js.id=id; js.src=b+"embed.js"; q=gt.call(d,"script")[0]; q.parentNode.insertBefore(js,q) } })() </script>

  <button class="primary-button confirm-button">
    <%= link_to 'Confirm your plan', getstarted_pro_confirm_path %>
  </button>
</div>

app/views/getstarted/pro_confirm.html.erb
pro_confirm.html.erb

app/views/getstarted/thankyou.html.erb
<div class="text-center" id="thankyou" >
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h1>Thank You</h1>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Growth for architect - IGGROW</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'favicon.png' %>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
    <!-- Stylesheet -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://js.stripe.com/v3/', 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="67f388c1-3991-45b3-8953-cbe2a179893d";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-103187008-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-103187008-1');
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/blog.html.erb
<!-- Navbar -->
<%= render 'shared/navbar_pages' %>

<div id="blog">
  <div class="banner-pages">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h1>Instagram Marketing Stratedy, Tips, Tools and Guides</h1>
        </div>
      </div>
    </div>
  </div> <!-- End .banner-pages -->

  <div class="pages-content">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h2>Under Construction</h2>
        </div>
      </div>
    </div>
  </div>


</div>

<!-- Footer -->
<%= render 'shared/footer_pages' %>

app/views/pages/jobs.html.erb
<!-- Navbar -->
<%= render 'shared/navbar_pages' %>

<div id="jobs">
  <div class="banner-pages">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h1>Want to start a career at IGGROW ?</h1>
        </div>
      </div>
    </div>
  </div>

  <div class="blog-content">
    <div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <h2>Under Construction</h2>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Footer -->
<%= render 'shared/footer_pages' %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="footer-top">
    <button class="secondary-button footer-top-button">
      <a href="#pricing">Commencez ici</a>
    </button>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row pl20">
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
            <a href="#banner" class="iggrow-logo">vima</a>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <ul>
            <li><a href="#why">Découvrir</a></li>
            <li><a href="#how">Services</a></li>
            <li><a href="#pricing">Produits</a></li>
            <li><a href="#contact">Contactez nous</a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <ul>
            <li><a href="/blog">Blog</a></li>
            <li><a href="/jobs">Jobs chez Vima</a></li>
            <li><a href="/terms">CGU</a></li>
            <li><a href="/faq">FAQ</a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <ul>
            <li>Suivez-nous :</li>
            <li>
              <a href="https://www.instagram.com/worldwildarchitecture" target="_blank">
                <i class="fab fa-instagram" aria-hidden="true"></i>
                Instagram
              </a>
            </li>
            <li>
              <a href="https://www.facebook.com/iggrow_" target="_blank">
                <i class="fab fa-facebook-square" aria-hidden="true"></i>
                Facebook
              </a>
            </li>
          </ul>
        </div> <!-- End .col-xs-12 .col-sm-12 .col-md-3 .col-lg-3 -->
      </div> <!-- End .row -->
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="vcenter text-center">
            <div class="made-with-love">
              &copy; 2018 vima -
              Made with <%= image_tag("emoji-heart.png", class: "emoji") %>
              in Belgium <%= image_tag("emoji-flag.png", class: "emoji") %>
            </div> <!-- End made-with-love -->
          </div> <!-- End .vcenter -->
        </div>
      </div>
    </div> <!-- End .container -->
  </div> <!-- End .footer-bottom -->
</div> <!-- End #footer -->

app/views/shared/_footer_pages.html.erb
<div id="footer">
  <div class="footer-top">
    <button class="secondary-button footer-top-button">
      <a href="/#pricing">Get Started</a>
    </button>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="row pl20">
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <a href="/#banner" class="iggrow-logo">iggrow</a>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <ul>
            <li><a href="/#why">Discover</a></li>
            <li><a href="/#how">How it works</a></li>
            <li><a href="/#pricing">Pricing</a></li>
            <li><a href="/#contact">Contact us</a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <ul>
            <li><a href="/blog">Blog</a></li>
            <li><a href="/jobs">Jobs at iggrow</a></li>
            <li><a href="/terms">Terms and conditions</a></li>
            <li><a href="/faq">FAQ</a></li>
          </ul>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
          <ul>
            <li>Follow us :</li>
            <li>
              <a href="https://www.instagram.com/iggrow_" target="_blank">
                <i class="fa fa-instagram" aria-hidden="true"></i>
                Instagram
              </a>
            </li>
            <li>
              <a href="https://www.facebook.com/iggrow_" target="_blank">
                <i class="fa fa-facebook-square" aria-hidden="true"></i>
                Facebook
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <div class="vcenter text-center">
            <div class="made-with-love">
              &copy; 2018 IGGROW -
              Made with <%= image_tag("emoji-heart.png", class: "emoji") %>
              in Belgium <%= image_tag("emoji-flag.png", class: "emoji") %>
            </div> <!-- End made-with-love -->
          </div> <!-- End .vcenter -->
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<div class="navbar-recovr hidden-sm hidden-xs">
  <a href="#banner" class="iggrow-logo">
    vima
  </a>
  <div class="nav-container">
    <div class="nav-element">
      <a href="#why">
        <%= t('landing.navbar.discover') %>
      </a>
    </div> <!-- End .nav-element -->
    <div class="nav-element">
      <a href="#how">
        <%= t('landing.navbar.how_it_works') %>
      </a>
    </div> <!-- End .nav-element -->
    <div class="nav-element">
      <a href="#pricing">
        <%= t('landing.navbar.pricing') %>
      </a>
    </div> <!-- End .nav-element -->
    <div class="nav-element">
      <a href="#contact">
        <%= t('landing.navbar.contact_us') %>
      </a>
    </div> <!-- End .nav-element -->
  </div>
</div>

<div class="navbar-recovr-mobile hidden-md hidden-lg">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-12">
        <%= image_tag("iggrow-logo.svg", class: "nav-logo-mobile") %>
      </div>
    </div>
  </div>
</div>